services:
  django:
    build:
      context: .
      dockerfile: ./docker/local/django.Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: /start


  db:
    image: postgres:14.4
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    volumes:
      - library_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  library_db_data:
